server:
  port: 41000
  servlet:
    context-path: /storage-service

spring:
  application:
    name: storage-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54320}/${DB_NAME:postgres}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      max-lifetime: 600000
      pool-name: PostgresHikariPool
    jpa:
      open-in-view: false
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          order_inserts: true
          order_updates: true
          jdbc:
            fetch_size: 500
            batch_size: 100
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml

